# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: show_score_board.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16show_score_board.proto\"-\n\nscoreBoard\x12\x0f\n\x07players\x18\x01 \x03(\t\x12\x0e\n\x06scores\x18\x02 \x03(\x05')



_SCOREBOARD = DESCRIPTOR.message_types_by_name['scoreBoard']
scoreBoard = _reflection.GeneratedProtocolMessageType('scoreBoard', (_message.Message,), {
  'DESCRIPTOR' : _SCOREBOARD,
  '__module__' : 'show_score_board_pb2'
  # @@protoc_insertion_point(class_scope:scoreBoard)
  })
_sym_db.RegisterMessage(scoreBoard)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCOREBOARD._serialized_start=26
  _SCOREBOARD._serialized_end=71
# @@protoc_insertion_point(module_scope)
